# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
steps:
  - task: AzureCLI@2
    displayName: 'tf log'
    inputs:
      azureSubscription: '$(ado_service_connection_rg)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'export TF_LOG="DEBUG"; export TF_LOG_PATH="/tmp/terraform.log"'
      
  - task: AzureCLI@2
    displayName: 'ls tf'
    inputs:
      azureSubscription: '$(ado_service_connection_rg)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'pwd; ls $(System.DefaultWorkingDirectory); ls $(System.DefaultWorkingDirectory)/$(terraform_workingdir); ls -l /opt/hostedtoolcache/terraform/0.14.7/x64/'
      
  - task: TerraformTaskV2@2
    displayName: 'Terraform init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      backendServiceArm: '$(ado_service_connection_rg)'
      backendAzureRmResourceGroupName: '$(terraform_st_resource_group)'
      backendAzureRmStorageAccountName: '$(terraform_st_storage_account)'
      backendAzureRmContainerName: '$(terraform_st_container_name)'
      backendAzureRmKey: '$(terraform_st_key)'
    continueOnError: true
      
  - task: AzureCLI@2
    displayName: 'tf log print'
    inputs:
      azureSubscription: '$(ado_service_connection_rg)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'cat /tmp/terraform.log'
